[package]
name = "unityjaeger/scrivener"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
include = [
	"default.project.json",
	"wally.toml",
	"README.md",
    "main.luau"
]
exclude = ["**"]